### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by vaastav** [Blueprint-uServices/blueprint#1]
In GitLab by @JonathanMace on Aug 23, 2023, 04:05

This issue outlines the concrete work associated with the upcoming Blueprint milestones

# Milestone 1: Barebones Deployment with GRPC

Workflow spec services that can be deployed over GRPC, thereby running in separate processes.  Manually start the processes and submit a workload on the same machine.

Plugins required:
- [x] Workflow Spec Services Plugin
- [x] Golang Process Plugin
- [x] GRPC Plugin

Detailed task list:
- Golang Process Plugin
  - Tidying
    - [x] Update DICodeBuilder and Impl to add an ImportType method for convenience.  Remove the current Import implementation on DICodeBuilder and replace its usage with the gogen.Imports struct.  Simplify template generation
    - [x] Update the workflow spec plugin implementation to use the above, simplifying the implementation.  Also move codegen parts into a codegen subdir
  - Generated DI code
    - [x] Generated graph() method must declare all string args in di.  It should return the container (with Get method), not graph.
  - DI runtime graph/container
    - [x] container Get method should receive a context so that things like server goroutines can shutdown on process exit
    - [x] Container should have a waitgroup so that callers can wait on things like server goroutines
    - [x] Add an Await method on the DI container to wait for the waitgroup
  - Generated main method
    - [x] Main-method generation that takes cmd line args, puts them in a map, and invokes the graph function
    - [x] Process IRNode should keep track of which nodes must be explicitly instantiated.  Generated main() should do that instantiation by calling get() after the definitions.
    - [x] Generated main method should create a context for cancellation, pass it to the DI container, and await the waitgroup after getting all definitions
- GRPC Plugin
  - Client and Server Handler
    - [x] Finish implementing generated client methods; see if using copier is sufficient
    - [x] Finish implementing generated server methods
    - [x] Implement instantiation code for client, making use of the ctx above
    - [x] Implement instantiation code for server, making use of the ctx and waitgroup above
  - Configuration
    - [ ] Add a general IRNode representing **runtime** configuration -- ie specifying that this config should come from runtime
    - [ ] Add config for timeout, allowing both a runtime configured value, or a directly configured value

# Milestone 2: Minimally Featured Deployment

Workflow spec services that can be wrapped with tracing and clientpools, can be deployed over GRPC, and can utilize memcached.  Processes are deployed in docker containers and a docker-compose file is created.  With these plugins implemented, we should have touched all the various kinds of plugins and concepts currently considered by Blueprint.

Plugins required:
- [ ] OpenTelemetry w/ Jaeger backend
- [ ] Clientpools
- [ ] Runtime stdlib + Cache
- [ ] Memcached
- [ ] Docker container image
- [ ] Docker compose

Detailed task list:
- TODO: many tasks associated with the above

# Milestone 3: Release-level

Plugins required:
- Databases, etc. and initializing them (e.g. with schemas), MongoDB
- Metrics collection, log collection
- HTTP frontend

# Milestone 4: Fully-featured parity with Blueprint v1

Plugins required:
- Kubernetes deployment
- Manual replication and load balancing
- Platform Replication and load balancing using kubernetes
- Circuit breaker prototype
- Async / queue-based services, RabbitMQ
- Configurable RPC retries
- other DBs, e.g. MySQL
- other caches, e.g. Redis
- georeplication

# Milestone 5: wishlist

Plugins required:
- storage backend, e.g. HDFS, Cassandra
- Sidecar pattern + Envoy
- other queues, e.g. Kafka
- Thrift support
- cloud deployment

Other functionality:
- workloads
- fault injection

# Additional:

Desirable tasks:
- [ ] Rename Scope to Namespace in code, comments, and docs
- [ ] Rename pointer, src, and dst to something else
- [ ] General approach to testing, even if not fully done
- [ ] Example applications
- [ ] Documentation and tutorials
